openapi: 3.1.0
info:
  title: Genie Lab API
  version: 1.0.0
  description: A simple, minimal API for managing an ai agent.

servers:
  - url: http://localhost:3000/v1
    description: Local development server

tags:
  - name: auth-management
  - name: organisation-management

paths:
  /login:
    post:
      description: Login to an organisation
      summary: Login to an organisation
      tags:
        - auth-management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: The user successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid input

  /organisation:
    post:
      description: Create an organisation and a root user
      summary: Create an organisation
      tags:
        - organisation-management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganisationRequest'
      responses:
        '201':
          description: The organisation and the root user successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationResponse'
        '400':
          description: Invalid input

components:
  schemas:
    CreateOrganisationRequest:
      type: object
      required:
        - name
        - phone
        - address
        - rootUser
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: The name of the organisation
          example: Acme Corp
        phone:
          type: string
          description: The phone number of the organisation
          example: 0412345678
        address:
          type: string
          minLength: 10
          maxLength: 100
          description: The address of the organisation
          example: 10 example st, Brisbane
        rootUser:
          $ref: '#/components/schemas/LoginRequest'
    OrganisationResponse:
      type: object
      required:
        - id
        - name
        - phone
        - address
      properties:
        id:
          type: string
          description: The unique identifier of the organisation
          example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
        name:
          type: string
          description: The name of the organisation
          example: Acme Corp
        phone:
          type: string
          description: The phone number of the organisation
          example: 0412345678
        address:
          type: string
          description: The address of the organisation
          example: 10 example st, Brisbane
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: The email of the root user
          example: lisa@example.com
        password:
          type: string
          minLength: 6
          description: The password of the root user
          example: 123456
    LoginResponse:
      type: object
      required:
        - token
        - expiration
      properties:
        token:
          type: string
          description: The JWT token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQss
        expiration:
          type: string
          description: The expiration date of the JWT token
          example: 2023-01-01T00:00:00.000Z
