openapi: 3.1.0
info:
  title: Genie Lab API
  version: 1.0.0
  description: A simple, minimal API for managing an ai agent.

servers:
  - url: http://localhost:3000/v1
    description: Local development server

tags:
  - name: auth-management
  - name: organisation-management
  - name: instruction-management

paths:
  /auth/login:
    post:
      description: Login to an organisation
      summary: Login to an organisation
      tags:
        - auth-management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: The user successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid input

  /organisation:
    post:
      description: Create an organisation and a root user
      summary: Create an organisation
      tags:
        - organisation-management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganisationRequest'
      responses:
        '201':
          description: The organisation and the root user successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationResponse'
        '400':
          description: Invalid input
  
  /organisation/:organisationId/instructions:
    get:
      description: Get all instructions with their latest versions
      summary: Get all instructions
      tags:
        - instruction-management
      responses:
        '200':
          description: The instructions successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionListResponse'
    post:
      description: Create an instruction and its first version
      summary: Create an instruction
      tags:
        - instruction-management
      parameters:
        - $ref: '#/components/parameters/organisationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInstructionRequest'
      responses:
        '201':
          description: The instruction successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionResponse'
        '400':
          description: Invalid input
  /organisation/:organisationId/instructions/:instructionId:
    get:
      description: Get an instruction with its versions
      summary: Get an instruction
      tags:
        - instruction-management
      parameters:
        - $ref: '#/components/parameters/organisationId'
        - $ref: '#/components/parameters/instructionId'
      responses:
        '200':
          description: The instruction successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionDetailResponse'
    put:
      description: Update an instruction
      summary: Update an instruction
      tags:
        - instruction-management
      parameters:
        - $ref: '#/components/parameters/organisationId'
        - $ref: '#/components/parameters/instructionId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInstructionRequest'
      responses:
        '200':
          description: The instruction successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructionResponse'
        '400':
          description: Invalid input

components:
  parameters:
    organisationId:
      in: path
      name: organisationId
      description: The unique identifier of the organisation
      required: true
      schema:
        type: string
        example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
    instructionId:
      in: path
      name: instructionId
      description: The unique identifier of the instruction
      required: true
      schema:
        type: string
        example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
  schemas:
    CreateOrganisationRequest:
      type: object
      required:
        - name
        - phone
        - address
        - rootUser
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: The name of the organisation
          example: Acme Corp
        phone:
          type: string
          description: The phone number of the organisation
          example: 0412345678
        address:
          type: string
          minLength: 10
          maxLength: 100
          description: The address of the organisation
          example: 10 example st, Brisbane
        rootUser:
          $ref: '#/components/schemas/LoginRequest'
    OrganisationResponse:
      type: object
      required:
        - id
        - name
        - phone
        - address
      properties:
        id:
          type: string
          description: The unique identifier of the organisation
          example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
        name:
          type: string
          description: The name of the organisation
          example: Acme Corp
        phone:
          type: string
          description: The phone number of the organisation
          example: 0412345678
        address:
          type: string
          description: The address of the organisation
          example: 10 example st, Brisbane
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: The email of the root user
          example: lisa@example.com
        password:
          type: string
          minLength: 6
          description: The password of the root user
          example: 123456
    LoginResponse:
      type: object
      required:
        - token
        - expiration
      properties:
        token:
          type: string
          description: The JWT token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQss
        expiration:
          type: string
          description: The expiration date of the JWT token
          example: 2023-01-01T00:00:00.000Z
    CreateInstructionRequest:
      type: object
      required:
        - name
        - description
        - type
        - content
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: The name of the instruction
          example: Generate a python script
        description:
          type: string
          minLength: 1
          maxLength: 1000
          description: The description of the instruction
          example: Generate a python script that generates a random number
        type:
          type: string
          enum:
            - Personality
            - Procedure
            - Guardian
          description: The type of the instruction
          example: Procedure
        content:
          type: string
          minLength: 1
          maxLength: 5000
          description: The content of the instruction
          example: Generate a python script that generates a random number
    UpdateInstructionRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: The name of the instruction
          example: Generate a python script
        description:
          type: string
          minLength: 1
          maxLength: 1000
          description: The description of the instruction
          example: Generate a python script that generates a random number
        content:
          type: string
          minLength: 1
          maxLength: 5000
          description: The content of the instruction
          example: Generate a python script that generates a random number
    InstructionResponse:
      type: object
      required:
        - id
        - name
        - description
        - type
      properties:
        id:
          type: string
          description: The unique identifier of the instruction
          example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
        name:
          type: string
          description: The name of the instruction
          example: Generate a python script
        description:
          type: string
          description: The description of the instruction
          example: Generate a python script that generates a random number
        type:
          type: string
          enum:
            - Personality
            - Procedure
            - Guardian
          description: The type of the instruction
          example: Procedure
        latestVersion:
          $ref: '#/components/schemas/InstructionVersionResponse'
    InstructionListResponse:
      type: object
      required:
        - items
        - total
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/InstructionResponse'
          description: The list of instructions
        total:
          type: integer
          description: The total number of instructions
          example: 10
    InstructionDetailResponse:
      type: object
      required:
        - id
        - name
        - description
        - type
        - versions
      properties:
        id:
          type: string
          description: The unique identifier of the instruction
          example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
        name:
          type: string
          description: The name of the instruction
          example: Generate a python script
        description:
          type: string
          description: The description of the instruction
          example: Generate a python script that generates a random number
        type:
          type: string
          enum:
            - Personality
            - Procedure
            - Guardian
          description: The type of the instruction
          example: Procedure
        versions:
          type: array
          items:
            $ref: '#/components/schemas/InstructionVersionResponse'
          description: The versions of the instruction
    InstructionVersionResponse:
      type: object
      required:
        - id
        - version
        - content
      properties:
        id: 
          type: string
          description: The unique identifier of the instruction version
          example: 58c4012e-37eb-4b62-bbf8-8d6c0b7e6de6
        version:
          type: integer
          description: The version of the instruction
          example: 1
        content:
          type: string
          description: The content of the instruction
          example: Generate a python script that generates a random number
        